### ISSUE TITLE
Problem for put stlye

### ISSUE THREAD

**Issue by JulGotheKey** [arkon/ng-sidebar#88]
Hello !
I'm new in the Angular community and i just want to know, how  do you put some css/style inside your ng-sidebar ? 
For exemple i just want to change the background color of my sidebar via my component.css like this : 
`
ng-sidebar {
    background: greenyellow;
}
`

**Comment by arkon** [comment]
In theory, you could just write something like:

```css
.ng-sidebar { background: greenyellow; }
```

You can see all the various class names [here in the README](https://github.com/arkon/ng-sidebar#styling).

You can also add your own class name to the sidebar element by doing something like this:

```typescript
<ng-sidebar [sidebarClass]="'my-class'">...</ng-sidebar>
```
```css
.my-class { background: greenyellow; }
```
