### ISSUE TITLE
Size of sidebar

### ISSUE THREAD

**Issue by PatKayongo** [arkon/ng-sidebar#95]
How does one change the width of the sidebar?

**Comment by arkon** [comment]
By default, it should just expand to fit your content.

If you want to set a specific width, just style it with CSS with something like the following:

```css
:host >>> .ng-sidebar {
  width: 300px;  
}
```
